; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
data_dir = spiffs

[env:unihiker_k10]
platform = unihiker
board = unihiker_k10
framework = espidf
board_build.flash_mode = dio
board_build.psram = enable
board_build.esp-idf.sdkconfig_path = sdkconfig.unihiker_k10
board_build.partitions = src/partitions.csv
board_build.spiffs_dir = spiffs
monitor_speed = 115200
; For better performance
build_unflags = -Os
build_flags = 
    -O2
    -DCORE_DEBUG_LEVEL=3 ;info
    -DLOG_LOCAL_LEVEL=ESP_LOG_VERBOSE
;build_type = debug